apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vulnerabilities.snyk.io
spec:
  group: snyk.io
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            title:
              type: string
            id:
              type: string
            path:
              type: string
            kind:
              type: string
            resource:
              type: string
            image:
              type: string
            url:
              type: string
            description:
              type: string
            package:
              type: string
            version:
              type: string
            severity:
              type: string
            isUpgradable:
              type: boolean
            language:
              type: string
              nullable: true
            packageManager:
              type: string
              nullable: true
            publicationTime:
              type: string
              nullable: true
            disclosureTime:
              type: string
              nullable: true
            cvssV3:
              type: string
              nullable: true
            cvssScore:
              type: number
              nullable: true
  scope: Namespaced
  names:
    plural: vulnerabilities
    singular: vulnerability
    kind: Vulnerability
    shortNames:
      - vuln
      - vulns
  additionalPrinterColumns:
    - name: Title
      type: string
      description: The title of the vulnerability
      JSONPath: .spec.title
    - name: ID
      type: string
      description: The id of the vulnerability in Snyk
      JSONPath: .spec.id
      priority: 1
    - name: Kind
      type: string
      description: The Kind of the workload with the vulnerabile image
      JSONPath: .spec.kind
      priority: 1
    - name: Workload
      type: string
      description: The workload with the vulnerabile image
      JSONPath: .spec.resource
      priority: 1
    - name: Image
      type: string
      description: The image with the vulnerability
      JSONPath: .spec.image
    - name: Package
      type: string
      description: The affected package
      JSONPath: .spec.package
    - name: Severity
      type: string
      description: The severity of the vulnerability
      JSONPath: .spec.severity
